name: sma_app
description: "A new Flutter project that implements an expense tracker app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.66.0
  intl: ^0.20.1
  flutter_colorpicker: ^1.0.3
  uuid: ^4.5.1

  firebase_core: ^2.32.0
  cloud_firestore: ^4.11.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/